In [2]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/f9/14/67e9b2b2379cb530c0412123a674d045eca387dfcfa7db1c0028857b0a66/tensorflow-2.16.1-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/bf/45/c961e3cb6ddad76b325c163d730562bb6deb1ace5acbed0306f5fbefb90e/flatbuffers-24.3.7-py2.py3-none-any.whl.metadata
  Obtaining dependency information for gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 from https://files.pythonhosted.org/packages/fa/39/5aae571e

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.0/227.0 MB 8.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 1.2 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 26.2 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 25.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.8 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 23.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.8/389.8 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.2/394.2 kB 20.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 24.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 24.3 MB/s eta 0:00:0

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

### Sentences

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### Vector size

In [6]:
voc_size=10000

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8354, 7660, 1035, 4559], [8354, 7660, 1035, 4819], [8354, 1794, 1035, 9159], [1009, 3463, 9722, 6405, 4499], [1009, 3463, 9722, 6405, 5813], [7856, 8354, 6127, 1035, 3991], [7419, 7918, 3510, 6405]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8354 7660 1035 4559]
 [   0    0    0    0 8354 7660 1035 4819]
 [   0    0    0    0 8354 1794 1035 9159]
 [   0    0    0 1009 3463 9722 6405 4499]
 [   0    0    0 1009 3463 9722 6405 5813]
 [   0    0    0 7856 8354 6127 1035 3991]
 [   0    0    0    0 7419 7918 3510 6405]]


### Embedding Layer

In [17]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_shape=(sent_length,)))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 514ms/step
[[[-3.46348509e-02  1.04036182e-03  9.86766815e-03 -2.18022615e-04
    4.09936942e-02 -6.91156462e-03 -3.80716547e-02 -1.01014487e-02
    3.09529044e-02 -2.40746029e-02]
  [-3.46348509e-02  1.04036182e-03  9.86766815e-03 -2.18022615e-04
    4.09936942e-02 -6.91156462e-03 -3.80716547e-02 -1.01014487e-02
    3.09529044e-02 -2.40746029e-02]
  [-3.46348509e-02  1.04036182e-03  9.86766815e-03 -2.18022615e-04
    4.09936942e-02 -6.91156462e-03 -3.80716547e-02 -1.01014487e-02
    3.09529044e-02 -2.40746029e-02]
  [-3.46348509e-02  1.04036182e-03  9.86766815e-03 -2.18022615e-04
    4.09936942e-02 -6.91156462e-03 -3.80716547e-02 -1.01014487e-02
    3.09529044e-02 -2.40746029e-02]
  [ 4.53752913e-02  6.35540485e-03 -6.10323995e-03  3.27641107e-02
   -4.55806032e-02  1.40882991e-02 -6.68748468e-03 -4.60236669e-02
   -2.60941740e-02  1.25113390e-02]
  [ 3.97754833e-03  4.25113477e-02 -2.44438890e-02 -6.95694610e-03
   -3.96263376e-02 -1.12188831e-02 -3.749262

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 8354, 7660, 1035, 4559], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[[-0.03463485  0.00104036  0.00986767 -0.00021802  0.04099369 -0.00691156
  -0.03807165 -0.01010145  0.0309529  -0.0240746 ]
 [-0.03463485  0.00104036  0.00986767 -0.00021802  0.04099369 -0.00691156
  -0.03807165 -0.01010145  0.0309529  -0.0240746 ]
 [-0.03463485  0.00104036  0.00986767 -0.00021802  0.04099369 -0.00691156
  -0.03807165 -0.01010145  0.0309529  -0.0240746 ]
 [-0.03463485  0.00104036  0.00986767 -0.00021802  0.04099369 -0.00691156
  -0.03807165 -0.01010145  0.0309529  -0.0240746 ]
 [ 0.04537529  0.0063554  -0.00610324  0.03276411 -0.0455806   0.0140883
  -0.00668748 -0.04602367 -0.02609417  0.01251134]
 [ 0.00397755  0.04251135 -0.02444389 -0.00695695 -0.03962634 -0.01121888
  -0.03749262 -0.04702077 -0.02759885  0.04969777]
 [-0.01132225 -0.01676442  0.04194054 -0.01062246  0.03024802  0.02093674
   0.04841015 -0.00920471 -0.01563631  0.04630958]
 [ 0.02661098  0.01811397 -0.02343627 -0.01229504  0.04986386 -0.04315249
   0.02461114 